function ConvertTo-ChannelForgeExternalEvidenceObservation {
    [CmdletBinding()]
    param([Parameter(Mandatory)][System.Collections.IDictionary]$InputObject)
    $top=@('ContractVersion','ObservationId','ObservationStatus','ObservationKind','EntityType','AdapterId','AdapterVersion','ParserVersion','SourceId','SourceFamily','EvidenceClass','SourceRelationship','SourceRecordReference','ProvisionalSubjectKey','SourceChannelReference','BindingContext','FieldObservations','SourceDataTimeUtc','ObservationTimeUtc','FetchTimeUtc','InputArtifactFingerprint','ReasonCodes','RedactedFields','ReadOnly')
    foreach($k in $InputObject.Keys){if($k -notin $top){throw "Unknown top-level field '$k'."}}
    $contract='ChannelForgeExternalEvidenceObservation/v1'
    $allowed=@{ ObservationStatus=@('Observed','SourceUnavailable','Rejected'); ObservationKind=@('ScheduleEvent','ChannelSchedule','ProgrammeMetadata','EventStatus','Availability','Other'); EntityType=@('Programme','Event','Channel','Source','Other'); EvidenceClass=@('OfficialBroadcaster','OfficialOrganizer','ProviderXMLTV','ConfiguredTrustedXMLTV','TrustedSecondarySchedule','AEDDerived','Heuristic','Other'); SourceRelationship=@('Authoritative','Independent','Mirror','Unknown'); FieldName=@('Title','Subtitle','Description','Category','ScheduledStartUtc','UpdatedStartUtc','StopUtc','EventStatus','Participant','Competition','Venue','Network','ChannelAssignment'); ValueType=@('String','StringArray','Instant','Object') }
    function T($v,$n,[bool]$nullOk=$false) { if($null -eq $v){if($nullOk){return $null};throw "$n is required."};$s=([string]$v).Trim();if(-not $nullOk -and [string]::IsNullOrWhiteSpace($s)){throw "$n is required."};return $s }
    function I($v,$n) { if($null -eq $v -or [string]::IsNullOrWhiteSpace([string]$v)){return $null};$d=[datetimeoffset]::MinValue;if(-not [datetimeoffset]::TryParse([string]$v,[Globalization.CultureInfo]::InvariantCulture,[Globalization.DateTimeStyles]::AssumeUniversal -bor [Globalization.DateTimeStyles]::AdjustToUniversal,[ref]$d)){throw "$n must be an ISO-8601 instant."};return $d.ToUniversalTime().ToString("yyyy-MM-dd'T'HH:mm:ss'Z'",[Globalization.CultureInfo]::InvariantCulture) }
    foreach($n in @('ObservationStatus','ObservationKind','EntityType','AdapterId','AdapterVersion','ParserVersion','SourceId','SourceFamily','EvidenceClass','SourceRelationship','FieldObservations','ReasonCodes','RedactedFields')){if(-not $InputObject.Contains($n)){throw "Missing $n."}}
    foreach($n in @('ObservationStatus','ObservationKind','EntityType','EvidenceClass','SourceRelationship')){if($allowed[$n] -notcontains [string]$InputObject[$n]){throw "Invalid $n."}}
    $binding=$null;if($InputObject.Contains('BindingContext') -and $null -ne $InputObject.BindingContext){$b=$InputObject.BindingContext;if($b -isnot [System.Collections.IDictionary]){throw 'BindingContext must be an object.'};foreach($k in $b.Keys){if($k -notin @('PlaylistId','ChannelReference','StationReference','BindingKind')){throw "Unknown BindingContext field '$k'."}};$binding=[ordered]@{PlaylistId=T $b.PlaylistId 'BindingContext.PlaylistId' $true;ChannelReference=T $b.ChannelReference 'BindingContext.ChannelReference' $true;StationReference=T $b.StationReference 'BindingContext.StationReference' $true;BindingKind=T $b.BindingKind 'BindingContext.BindingKind' $true};if($binding.BindingKind -notin @($null,'SourceScoped','Shared','Unbound')){throw 'Invalid BindingKind.'}}
    $adapter=T $InputObject.AdapterId AdapterId;$source=T $InputObject.SourceId SourceId;$family=T $InputObject.SourceFamily SourceFamily
    foreach($v in @($adapter,$source,$family)){if($v -notmatch '^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$'){throw 'Unsafe logical identifier.'}}
    foreach($f in @($InputObject.FieldObservations)){if($f -isnot [System.Collections.IDictionary]){throw 'FieldObservation must be an object.'};foreach($k in $f.Keys){if($k -notin @('FieldName','ValueType','NormalizedValue','OriginalValueOrFingerprint','SourceDataTimeUtc','ObservationTimeUtc','ReasonCodes','Redacted')){throw "Unknown FieldObservation field '$k'."}}}
    $fields=[System.Collections.Generic.List[object]]::new();foreach($f in @($InputObject.FieldObservations)){if($f -isnot [System.Collections.IDictionary]){throw 'FieldObservation must be an object.'};$fn=T $f.FieldName FieldName;if($allowed.FieldName -notcontains $fn){throw "Unsupported FieldName $fn."};$vt=T $f.ValueType ValueType;if($allowed.ValueType -notcontains $vt){throw 'Invalid ValueType.'};$v=$f.NormalizedValue;if($vt -eq 'String' -and $null -ne $v){$v=T $v NormalizedValue};if($vt -eq 'StringArray'){$v=@($v|ForEach-Object{T $_ NormalizedValue}|Sort-Object -Unique)};if($vt -eq 'Instant' -and $null -ne $v){$v=I $v NormalizedValue};$r=@($f.ReasonCodes|ForEach-Object{T $_ ReasonCode}|Sort-Object -Unique);[void]$fields.Add([ordered]@{FieldName=$fn;ValueType=$vt;NormalizedValue=$v;OriginalValueOrFingerprint=T $f.OriginalValueOrFingerprint OriginalValueOrFingerprint $true;SourceDataTimeUtc=I $f.SourceDataTimeUtc FieldSourceDataTimeUtc;ObservationTimeUtc=I $f.ObservationTimeUtc FieldObservationTimeUtc;ReasonCodes=$r;Redacted=[bool]$f.Redacted})}
    $sourceRecord = T $InputObject.SourceRecordReference SourceRecordReference $true
    $provisional = T $InputObject.ProvisionalSubjectKey ProvisionalSubjectKey $true
    $sourceChannel = T $InputObject.SourceChannelReference SourceChannelReference $true
    foreach($v in @($sourceRecord,$provisional,$sourceChannel)){if($null -ne $v -and $v -match '://|@|[\\]'){throw 'External evidence reference contains a URL, credential, or private path.'}}
    $fields=@($fields|Sort-Object @{Expression={$_['FieldName']}},@{Expression={$_['ValueType']}},@{Expression={$_['OriginalValueOrFingerprint']}});$reasons=@($InputObject.ReasonCodes|ForEach-Object{T $_ ReasonCode}|Sort-Object -Unique);$redacted=@($InputObject.RedactedFields|ForEach-Object{T $_ RedactedField}|Sort-Object -Unique)
    $p=[ordered]@{ContractVersion=$contract;ObservationId='';ObservationStatus=[string]$InputObject.ObservationStatus;ObservationKind=[string]$InputObject.ObservationKind;EntityType=[string]$InputObject.EntityType;AdapterId=$adapter;AdapterVersion=T $InputObject.AdapterVersion AdapterVersion;ParserVersion=T $InputObject.ParserVersion ParserVersion;SourceId=$source;SourceFamily=$family;EvidenceClass=[string]$InputObject.EvidenceClass;SourceRelationship=[string]$InputObject.SourceRelationship;SourceRecordReference=T $InputObject.SourceRecordReference SourceRecordReference $true;ProvisionalSubjectKey=T $InputObject.ProvisionalSubjectKey ProvisionalSubjectKey $true;SourceChannelReference=T $InputObject.SourceChannelReference SourceChannelReference $true;BindingContext=$binding;FieldObservations=$fields;SourceDataTimeUtc=I $InputObject.SourceDataTimeUtc SourceDataTimeUtc;ObservationTimeUtc=I $InputObject.ObservationTimeUtc ObservationTimeUtc;FetchTimeUtc=I $InputObject.FetchTimeUtc FetchTimeUtc;InputArtifactFingerprint=T $InputObject.InputArtifactFingerprint InputArtifactFingerprint $true;ReasonCodes=$reasons;RedactedFields=$redacted;ReadOnly=$true}
    $id=[ordered]@{};foreach($e in $p.GetEnumerator()){if($e.Key -notin @('ObservationId','FetchTimeUtc','ObservationTimeUtc')){$id[$e.Key]=$e.Value}};$bytes=[Text.Encoding]::UTF8.GetBytes((ConvertTo-ChannelForgeCanonicalJson $id));$sha=[Security.Cryptography.SHA256]::Create();try{$p.ObservationId=([BitConverter]::ToString($sha.ComputeHash($bytes))).Replace('-','').ToLowerInvariant()}finally{$sha.Dispose()};return [pscustomobject]$p
}
