BeforeAll {
    $RepoRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
    $script:ManifestPath = Join-Path $RepoRoot 'src\ChannelForge\ChannelForge.psd1'
    $script:ModuleSourceRoot = Join-Path $RepoRoot 'src\ChannelForge'
    $script:PowerShellExecutable = Join-Path $PSHOME 'pwsh.exe'
    if (-not (Test-Path -LiteralPath $script:PowerShellExecutable -PathType Leaf)) { $script:PowerShellExecutable = (Get-Command pwsh -ErrorAction Stop).Source }

    $script:ChildScriptPath = Join-Path $TestDrive 'Invoke-PinnedHttpTransportAcquisitionChild.ps1'
    $script:ChildScript = {
param(
    [Parameter(Mandatory)][string]$ModulePath,
    [Parameter(Mandatory)][ValidateSet('success','304-default','304-authorized','redirect','status','content-type','missing-type','encoding','header-limit','body-limit','exact-limit','inactivity','total','cancel','header-timeout','tls-mismatch','source-id')][string]$Scenario
)
$ErrorActionPreference = 'Stop'
$manifestPath = Join-Path $ModulePath 'ChannelForge.psd1'
function Write-Result { param([object]$Value) $Value | ConvertTo-Json -Compress -Depth 10 }
function Details { param([System.Exception]$Exception)
    $e=$Exception
    while($null -ne $e.InnerException -and $null -eq $e.PSObject.Properties['Category']){$e=$e.InnerException}
    [pscustomobject]@{Category=if($e.PSObject.Properties['Category']){[string]$e.Category}else{$null};Phase=if($e.PSObject.Properties['Phase']){[string]$e.Phase}else{$null};StatusCode=if($e.PSObject.Properties['StatusCode']){$e.StatusCode}else{$null};Message=[string]$e.Message}
}
function Get-HelperType { $m=Get-Module ChannelForge; (& $m {Initialize-ChannelForgePinnedHttpTransport}).Type }
function New-Endpoint {
    $t=$script:Helper.Assembly.GetType('ChannelForge.Private.Transport.ChannelForgeValidatedEndpoint',$true,$false);$c=@($t.GetConstructors([Reflection.BindingFlags]::Instance -bor [Reflection.BindingFlags]::NonPublic)|? {$_.GetParameters().Count -eq 5})[0];$ips=[Collections.Generic.List[Net.IPAddress]]::new();$ips.Add([Net.IPAddress]::Parse('127.0.0.2'))|Out-Null;$c.Invoke([object[]]@([Uri]'https://transport.test.invalid/acquisition-test','transport.test.invalid',443,$false,$ips))
}
function New-Options { param([long]$Max=64,[string]$Policy='Require200',[bool]$AllowMissing=$false,[string]$Source='acquisition-test')
    $t=$script:Helper.Assembly.GetType('ChannelForge.Private.Transport.ChannelForgeHttpAcquisitionOptions',$true,$false);$p=$script:Helper.Assembly.GetType('ChannelForge.Private.Transport.ChannelForgeHttpStatusPolicy',$true,$false);$c=@($t.GetConstructors([Reflection.BindingFlags]::Instance -bor [Reflection.BindingFlags]::Public)|? {$_.GetParameters().Count -eq 5})[0];$c.Invoke([object[]]@($Source,[string[]]@('application/octet-stream'),$AllowMissing,$Max,[Enum]::Parse($p,$Policy)))
}
function New-Handler { param($Endpoint) $m=$script:Helper.GetMethod('CreatePinnedHandlerForTest',[Reflection.BindingFlags]::Static -bor [Reflection.BindingFlags]::NonPublic);$m.Invoke($null,[object[]]@($Endpoint)) }
function Start-Acquisition { param($Endpoint,$Options,$Handler,[TimeSpan]$Header,[TimeSpan]$Body,[TimeSpan]$Total,[Threading.CancellationToken]$Token) $m=$script:Helper.GetMethod('AcquireGetForTestAsync',[Reflection.BindingFlags]::Static -bor [Reflection.BindingFlags]::NonPublic);$m.Invoke($null,[object[]]@($Endpoint,$Options,$Handler,$Header,$Body,$Total,$Token)) }
function New-Certificates { param([string]$Name)
    $nb=[DateTimeOffset]::UtcNow.AddMinutes(-5);$na=[DateTimeOffset]::UtcNow.AddMinutes(30);$rk=[Security.Cryptography.RSA]::Create(2048);$rr=[Security.Cryptography.X509Certificates.CertificateRequest]::new('CN=ChannelForge Test Root',$rk,[Security.Cryptography.HashAlgorithmName]::SHA256,[Security.Cryptography.RSASignaturePadding]::Pkcs1);$rr.CertificateExtensions.Add([Security.Cryptography.X509Certificates.X509BasicConstraintsExtension]::new($true,$false,0,$true))|Out-Null;$root=$rr.CreateSelfSigned($nb,$na);$sk=[Security.Cryptography.RSA]::Create(2048);$sr=[Security.Cryptography.X509Certificates.CertificateRequest]::new("CN=$Name",$sk,[Security.Cryptography.HashAlgorithmName]::SHA256,[Security.Cryptography.RSASignaturePadding]::Pkcs1);$san=[Security.Cryptography.X509Certificates.SubjectAlternativeNameBuilder]::new();$san.AddDnsName($Name)|Out-Null;$sr.CertificateExtensions.Add($san.Build($false))|Out-Null;$unsigned=$sr.Create($root,$nb,$na,[byte[]](1,2,3,4));$pem="-----BEGIN CERTIFICATE-----`n"+[Convert]::ToBase64String($unsigned.RawData,[Base64FormattingOptions]::InsertLineBreaks)+"`n-----END CERTIFICATE-----";$server=[Security.Cryptography.X509Certificates.X509Certificate2]::CreateFromPem($pem,$sk.ExportPkcs8PrivateKeyPem());$pass='ChannelForge-test';$pfx=$server.Export([Security.Cryptography.X509Certificates.X509ContentType]::Pfx,$pass);$server.Dispose();$server=[Security.Cryptography.X509Certificates.X509Certificate2]::new($pfx,$pass,[Security.Cryptography.X509Certificates.X509KeyStorageFlags]::UserKeySet -bor [Security.Cryptography.X509Certificates.X509KeyStorageFlags]::Exportable -bor [Security.Cryptography.X509Certificates.X509KeyStorageFlags]::PersistKeySet);[pscustomobject]@{Root=$root;Server=$server;RootKey=$rk;ServerKey=$sk;Unsigned=$unsigned}
}
function Read-Headers { param([IO.Stream]$Stream) $b=[byte[]]::new(4096);$a=[Collections.Generic.List[byte]]::new();while($a.Count -lt 65536){$n=$Stream.Read($b,0,$b.Length);if($n -le 0){break};for($i=0;$i -lt $n;$i++){$a.Add($b[$i])};if($a.Count -ge 4 -and $a[$a.Count-4] -eq 13 -and $a[$a.Count-3] -eq 10 -and $a[$a.Count-2] -eq 13 -and $a[$a.Count-1] -eq 10){break}};[Text.Encoding]::ASCII.GetString($a.ToArray()) }
function Send-Response { param([IO.Stream]$Stream,[int]$Code,[string]$Reason,[byte[]]$Body,[string[]]$Headers=@(),[switch]$Chunked,[switch]$HeadersOnly) $h=[Collections.Generic.List[string]]::new();$h.Add("HTTP/1.1 $Code $Reason");$h.Add('Connection: close');foreach($x in $Headers){$h.Add($x)};if($Chunked){$h.Add('Transfer-Encoding: chunked')}elseif(-not $HeadersOnly){$h.Add("Content-Length: $($Body.Length)")};$hb=[Text.Encoding]::ASCII.GetBytes(($h -join "`r`n")+"`r`n`r`n");[void]$Stream.Write($hb,0,$hb.Length);[void]$Stream.Flush();if($HeadersOnly){return};if($Chunked -and $Body.Length -gt 0){$cb=[Text.Encoding]::ASCII.GetBytes(("{0:X}`r`n" -f $Body.Length));[void]$Stream.Write($cb,0,$cb.Length);[void]$Stream.Write($Body,0,$Body.Length);$tail=[Text.Encoding]::ASCII.GetBytes("`r`n0`r`n`r`n");[void]$Stream.Write($tail,0,$tail.Length)}elseif(-not $Chunked -and $Body.Length -gt 0){[void]$Stream.Write($Body,0,$Body.Length)};[void]$Stream.Flush() }
function Read-Body { param($Payload) $b=[byte[]]::new(128);$a=[Collections.Generic.List[byte]]::new();while(($n=$Payload.ResponseStream.Read($b,0,$b.Length)) -gt 0){for($i=0;$i -lt $n;$i++){$a.Add($b[$i])}};[Text.Encoding]::UTF8.GetString($a.ToArray()) }
function Run-Scenario { param([string]$Name)
    $canonicalHost='transport.test.invalid';$certName=if($Name -eq 'tls-mismatch'){'other.test.invalid'}else{$canonicalHost};$chain=New-Certificates $certName;$listener=[Net.Sockets.TcpListener]::new([Net.IPAddress]::Parse('127.0.0.2'),443);$listener.Start();$accept=$listener.AcceptTcpClientAsync();$ep=New-Endpoint;$handler=$null;$payload=$null;$client=$null;$ssl=$null;$request=$null;$null=($sniHolder=[pscustomobject]@{Name=$null});$serverError=$null;$cts=[Threading.CancellationTokenSource]::new()
    try {
        $handler=New-Handler $ep;$policy=[Security.Cryptography.X509Certificates.X509ChainPolicy]::new();$policy.TrustMode=[Security.Cryptography.X509Certificates.X509ChainTrustMode]::CustomRootTrust;$policy.RevocationMode=[Security.Cryptography.X509Certificates.X509RevocationMode]::NoCheck;$policy.CustomTrustStore.Add($chain.Root)|Out-Null;$handler.SslOptions.CertificateChainPolicy=$policy
        if($Name -eq 'source-id'){try{$null=New-Options -Source 'https://secret.invalid/token';return [pscustomobject]@{Success=$false;UnexpectedSuccess=$true}}catch{return [pscustomobject]@{Success=$true;Rejected=$true;Message=$_.Exception.Message}}}
        $opt=if($Name -eq '304-authorized'){New-Options -Policy Allow304MetadataOnly}elseif($Name -eq 'header-limit' -or $Name -eq 'body-limit' -or $Name -eq 'exact-limit'){New-Options -Max 5}elseif($Name -eq 'missing-type'){New-Options -AllowMissing $true}else{New-Options};$header=if($Name -eq 'header-timeout'){[TimeSpan]::FromMilliseconds(100)}else{[TimeSpan]::FromSeconds(2)};$bodyTimeout=if($Name -eq 'inactivity'){[TimeSpan]::FromMilliseconds(100)}else{[TimeSpan]::FromSeconds(2)};$total=[TimeSpan]::FromSeconds(3);if($Name -eq 'cancel'){$cts.CancelAfter(100)};$task=Start-Acquisition $ep $opt $handler $header $bodyTimeout $total $cts.Token;if(-not $accept.Wait(5000)){throw 'local listener received no connection'};$client=$accept.GetAwaiter().GetResult();$ssl=[Net.Security.SslStream]::new($client.GetStream(),$false);$so=[Net.Security.SslServerAuthenticationOptions]::new();$so.ServerCertificateSelectionCallback=[Net.Security.ServerCertificateSelectionCallback]{param($sender,$serverName)$sniHolder.Name=[string]$serverName;return $chain.Server}.GetNewClosure();try{$ssl.AuthenticateAsServerAsync($so).GetAwaiter().GetResult()}catch{$serverError=$_.Exception.Message;return [pscustomobject]@{Success=$false;ServerError=$serverError;Sni=$sniHolder.Name}}
        if($Name -eq 'header-timeout'){try{$null=$task.GetAwaiter().GetResult();return [pscustomobject]@{Success=$false;UnexpectedSuccess=$true}}catch{$d=Details $_.Exception;return [pscustomobject]@{Success=$false;Category=$d.Category;Phase=$d.Phase;Sni=$sniHolder.Name}}};$requestBytes=[byte[]]::new(8192);$requestReadTask=$ssl.ReadAsync($requestBytes,0,$requestBytes.Length);if($task.Wait(500) -and $task.IsFaulted){$d=Details $task.Exception;return [pscustomobject]@{Success=$false;Category=$d.Category;Phase=$d.Phase;StatusCode=$d.StatusCode;Sni=$sniHolder.Name}};if(-not $requestReadTask.Wait(5000)){throw 'local TLS server did not receive the HTTP request'};$request=[Text.Encoding]::ASCII.GetString($requestBytes,0,$requestReadTask.Result);$body=[Text.Encoding]::UTF8.GetBytes('hello');$code=200;$reason='OK';$headers=@('Content-Type: application/octet-stream');$chunk=$false;$only=$false;switch($Name){'304-default'{$code=304;$reason='Not Modified';$headers=@()};'304-authorized'{$code=304;$reason='Not Modified';$headers=@()};'redirect'{$code=302;$reason='Found';$headers=@('Location: https://redirect.test.invalid/next')};'status'{$code=404;$reason='Not Found';$headers=@()};'content-type'{$headers=@('Content-Type: text/plain')};'missing-type'{$headers=@()};'encoding'{$headers=@('Content-Type: application/octet-stream','Content-Encoding: gzip','Content-Encoding: br')};'header-limit'{$body=[Text.Encoding]::UTF8.GetBytes('hello world')};'body-limit'{$body=[Text.Encoding]::UTF8.GetBytes('abcdef');$chunk=$true};'exact-limit'{$body=[Text.Encoding]::UTF8.GetBytes('abcde');$chunk=$true};'inactivity'{$only=$true};'total'{$only=$true};'cancel'{$only=$true}};Send-Response $ssl $code $reason $body $headers -Chunked:$chunk -HeadersOnly:$only
        try{$payload=$task.GetAwaiter().GetResult()}catch{$d=Details $_.Exception;return [pscustomobject]@{Success=$false;Category=$d.Category;Phase=$d.Phase;StatusCode=$d.StatusCode;Sni=$sniHolder.Name;RequestLine=($request -split "`r?`n")[0]}}
        if($Name -eq 'inactivity' -or $Name -eq 'total' -or $Name -eq 'cancel'){try{if($Name -eq 'total'){Start-Sleep -Milliseconds 3200};$readCts=$null;if($Name -eq 'cancel'){$readCts=[Threading.CancellationTokenSource]::new();$readCts.CancelAfter(100);$null=$payload.ResponseStream.ReadAsync([byte[]]::new(32),0,32,$readCts.Token).GetAwaiter().GetResult()}else{$null=$payload.ResponseStream.Read([byte[]]::new(32),0,32)};return [pscustomobject]@{Success=$false;UnexpectedSuccess=$true}}catch{$d=Details $_.Exception;return [pscustomobject]@{Success=$false;Category=$d.Category;Phase=$d.Phase;Sni=$sniHolder.Name}}finally{if($null -ne $readCts){$readCts.Dispose()}}}
        [pscustomobject]@{Success=$true;StatusCode=$payload.StatusCode;Disposition=[string]$payload.StatusDisposition;ContentType=$payload.ContentType;Encodings=@($payload.ContentEncodings);HasPayload=$payload.HasPayload;ResponseStreamNull=$null -eq $payload.ResponseStream;Body=if($payload.HasPayload){Read-Body $payload}else{$null};Sni=$sniHolder.Name;RequestLine=($request -split "`r?`n")[0]}
    }finally{if($null -ne $payload){$payload.Dispose()};if($null -ne $ssl){$ssl.Dispose()};if($null -ne $client){$client.Dispose()};if($null -ne $handler){$handler.Dispose()};$cts.Dispose();$listener.Stop();$chain.Server.Dispose();$chain.Root.Dispose();$chain.ServerKey.Dispose();$chain.RootKey.Dispose();$chain.Unsigned.Dispose()}
}
try{Import-Module $manifestPath -Force;$script:Helper=Get-HelperType;if($Scenario -eq 'source-id'){try{$null=New-Options -Source 'https://secret.invalid/token';Write-Result @{Success=$false;UnexpectedSuccess=$true}}catch{Write-Result @{Success=$true;Rejected=$true;Message=$_.Exception.Message}}}else{Write-Result (Run-Scenario $Scenario)}}catch{$d=Details $_.Exception;Write-Result @{Success=$false;Category=$d.Category;Phase=$d.Phase;StatusCode=$d.StatusCode;Message=$d.Message;RequestLine=if($null -ne $request){($request -split "`r?`n")[0]}else{$null};Sni=$sniHolder.Name};exit 1}
}
    $script:ChildScript.ToString() | Set-Content -LiteralPath $script:ChildScriptPath -Encoding utf8

    function New-PinnedTransportAcquisitionModuleCopy {
        $modulePath = Join-Path $TestDrive ('ChannelForgePinnedAcquisition-' + [guid]::NewGuid().ToString('N'))
        New-Item -ItemType Directory -Path $modulePath -Force | Out-Null
        Get-ChildItem -LiteralPath $script:ModuleSourceRoot -Force | Copy-Item -Destination $modulePath -Recurse -Force
        $modulePath
    }
    function Invoke-PinnedTransportAcquisitionChild {
        param([Parameter(Mandatory)][string]$ModulePath,[Parameter(Mandatory)][string]$Scenario)
        $output=@(& $script:PowerShellExecutable -NoLogo -NoProfile -NonInteractive -File $script:ChildScriptPath -ModulePath $ModulePath -Scenario $Scenario 2>&1);$exit=$LASTEXITCODE;$lines=@($output|%{$s=([string]$_).Trim();if($s -match '"(Success|Category|Rejected)"'){$s}});if($lines.Count -lt 1){throw "acquisition child produced no JSON. ExitCode=$exit Output=$($output -join ' | ')"};$parsed=@($lines[-1]|ConvertFrom-Json);$r=@($parsed|? {$_.PSObject.Properties['Success'] -or $_.PSObject.Properties['Category'] -or $_.PSObject.Properties['Rejected']})[-1];if($null -eq $r){throw "acquisition child result had no recognized result object. ExitCode=$exit Output=$($output -join ' | ')"};$r
    }
}
Describe 'ChannelForge bounded HTTPS acquisition' {
    It 'streams 200 payloads with stable metadata and canonical TLS host' {$r=Invoke-PinnedTransportAcquisitionChild (New-PinnedTransportAcquisitionModuleCopy) 'success';$r.Success|Should -BeTrue -Because ($r|ConvertTo-Json -Compress);$r.StatusCode|Should -Be 200;$r.Disposition|Should -Be Payload;$r.ContentType|Should -Be 'application/octet-stream';$r.Body|Should -Be hello;$r.Sni|Should -Be 'transport.test.invalid';$r.RequestLine|Should -Match '^GET /acquisition-test HTTP/'}
    It 'rejects ordinary 304 and other non-success statuses without redirects' {$a=Invoke-PinnedTransportAcquisitionChild (New-PinnedTransportAcquisitionModuleCopy) '304-default';$b=Invoke-PinnedTransportAcquisitionChild (New-PinnedTransportAcquisitionModuleCopy) 'redirect';$c=Invoke-PinnedTransportAcquisitionChild (New-PinnedTransportAcquisitionModuleCopy) 'status';$a.Category|Should -Be RedirectRejected;$a.StatusCode|Should -Be 304;$b.Category|Should -Be RedirectRejected;$c.Category|Should -Be NonSuccessHttpStatus;$c.StatusCode|Should -Be 404}
    It 'surfaces authorized 304 as metadata only' {$r=Invoke-PinnedTransportAcquisitionChild (New-PinnedTransportAcquisitionModuleCopy) '304-authorized';$r.Success|Should -BeTrue;$r.Disposition|Should -Be MetadataOnly;$r.HasPayload|Should -BeFalse;$r.ResponseStreamNull|Should -BeTrue}
    It 'validates content type and preserves ordered encoding metadata' {$a=Invoke-PinnedTransportAcquisitionChild (New-PinnedTransportAcquisitionModuleCopy) 'content-type';$b=Invoke-PinnedTransportAcquisitionChild (New-PinnedTransportAcquisitionModuleCopy) 'missing-type';$c=Invoke-PinnedTransportAcquisitionChild (New-PinnedTransportAcquisitionModuleCopy) 'encoding';$a.Category|Should -Be UnsupportedContentType;$b.Body|Should -Be hello;@($c.Encodings)|Should -Be @('gzip','br');$c.Body|Should -Be hello}
    It 'enforces header and streamed bounds while accepting the exact limit' {$a=Invoke-PinnedTransportAcquisitionChild (New-PinnedTransportAcquisitionModuleCopy) 'header-limit';$b=Invoke-PinnedTransportAcquisitionChild (New-PinnedTransportAcquisitionModuleCopy) 'body-limit';$c=Invoke-PinnedTransportAcquisitionChild (New-PinnedTransportAcquisitionModuleCopy) 'exact-limit';$a.Category|Should -Be ResponseTooLarge;$a.Phase|Should -Be Headers;$b.Category|Should -Be ResponseTooLarge;$b.Phase|Should -Be Body;$c.Body|Should -Be abcde}
    It 'distinguishes inactivity, total deadline, and caller cancellation' {$a=Invoke-PinnedTransportAcquisitionChild (New-PinnedTransportAcquisitionModuleCopy) 'inactivity';$b=Invoke-PinnedTransportAcquisitionChild (New-PinnedTransportAcquisitionModuleCopy) 'total';$c=Invoke-PinnedTransportAcquisitionChild (New-PinnedTransportAcquisitionModuleCopy) 'cancel';$a.Category|Should -Be Timeout;$a.Phase|Should -Be BodyInactivity;$b.Category|Should -Be Timeout;$b.Phase|Should -Be Total;$c.Category|Should -Be Cancelled}
    It 'bounds header wait and preserves TLS hostname for the pinned IP connection' {$a=Invoke-PinnedTransportAcquisitionChild (New-PinnedTransportAcquisitionModuleCopy) 'header-timeout';$b=Invoke-PinnedTransportAcquisitionChild (New-PinnedTransportAcquisitionModuleCopy) 'success';$a.Category|Should -Be Timeout;$a.Phase|Should -Be Headers;$b.Sni|Should -Be 'transport.test.invalid'}
    It 'fails mismatched certificate validation and rejects URL-shaped source identity' {$a=Invoke-PinnedTransportAcquisitionChild (New-PinnedTransportAcquisitionModuleCopy) 'tls-mismatch';$b=Invoke-PinnedTransportAcquisitionChild (New-PinnedTransportAcquisitionModuleCopy) 'source-id';$a.Category|Should -Be TlsFailure;$b.Rejected|Should -BeTrue;$b.Message|Should -Not -Match 'secret|https?://'}
}