#
# Module manifest for module 'ChannelForge'
#
# Generated by: Jumpstile
#
# Generated on: 6/26/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'ChannelForge.psm1'

# Version number of this module.
ModuleVersion = '0.1.0'

# Supported PSEditions
CompatiblePSEditions = @('Core')

# ID used to uniquely identify this module
GUID = '8776bd44-01c7-46bb-ad94-6daebddd8a36'

# Author of this module
Author = 'Jumpstile'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) 2026 Jumpstile. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Source-of-truth IPTV lineup builder for IPTVBoss, Dispatcharr, and Plex'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '7.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module.
# None today: every runtime dependency (ConvertFrom-Json, Test-Json, etc.) ships
# in PowerShell 7 itself. Pester and PSScriptAnalyzer are development/CI
# tooling, not runtime dependencies of the module, so they are not listed here
# (see docs/developer/DEVELOPER_GUIDE.md for how their versions are pinned).
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module. Explicit list, kept in sync with
# src/ChannelForge/Public/*.ps1 -- see tests/unit/ModuleManifest.Tests.ps1,
# which fails if this list and the Public/ directory ever disagree.
FunctionsToExport = @(
    'Assert-ChannelForgeBackupSourcePath'
    'Assert-ChannelForgePathExists'
    'Assert-ChannelForgeReadPath'
    'Assert-ChannelForgeWritePath'
    'ConvertTo-ChannelForgeNormalizedChannel'
    'Export-ChannelForgeM3UPlaylist'
    'Import-ChannelForgeM3UPlaylist'
    'Import-ChannelForgeConfiguredXmltvSource'
    'Import-ChannelForgeXmltvSource'
    'Merge-ChannelForgeLineup'
    'Merge-ChannelForgeXmltvProgrammes'
    'New-ChannelForgeBuildContext'
    'New-ChannelForgeChannel'
    'New-ChannelForgeProgramme'
    'Read-ChannelForgeEpgSource'
    'Read-ChannelForgeProvider'
    'Resolve-ChannelForgeAlias'
    'Resolve-ChannelForgeProviderConfigPath'
    'Set-ChannelForgeChannelNumber'
)

# Cmdlets to export from this module. None: ChannelForge is a script module
# with no compiled (C#/binary) cmdlets.
CmdletsToExport = @()

# Variables to export from this module. None: ChannelForge does not
# intentionally export any module-scope variables.
VariablesToExport = @()

# Aliases to export from this module. None: ChannelForge does not define
# any command aliases.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('IPTV', 'M3U', 'XMLTV', 'IPTVBoss', 'Dispatcharr', 'Plex', 'PowerShell')

        # A URL to the license for this module.
        # LicenseUri = '' # No license file is tracked yet; do not claim one until docs/LICENSE exists.

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/Jumpstile/ChannelForge'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = '' # No per-version release notes are tracked yet; see ROADMAP.md and LESSONS_LEARNED.md instead.

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = '' # No updatable-help content is published for this module.

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
